Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -3,26 +3,51 @@
 
 name: Go
 
-on:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+    env:
+      GIN_MODE: release
 
-jobs:
+    on:
+      push:
+        branches: [ "main" ]
+      pull_request:
+        branches: [ "main" ]
 
-  build:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
+    jobs:
+      build:
+        runs-on: ubuntu-latest
 
-    - name: Set up Go
-      uses: actions/setup-go@v4
-      with:
-        go-version: '1.20'
+        permissions:
+          checks: write
 
-    - name: Build
-      run: go build -v ./...
+        steps:
+        - uses: actions/checkout@v3
 
-    - name: Test
-      run: go test -v ./...
+        - name: Set up Go
+          uses: actions/setup-go@v3
+          with:
+            go-version-file: 'go.mod'
+            cache: true
+
+        - name: Revive Action
+          uses: morphy2k/revive-action@v2.4.1
+
+        - name: Staticcheck
+          uses: dominikh/staticcheck-action@v1.3.0
+
+        - name: Build
+          run: |
+            go mod download
+            go install gotest.tools/gotestsum@latest
+
+        - name: Test
+          run: |
+            gotestsum --format=standard-verbose --junitfile=junit.xml
+
+        - name: Publish Test Report
+          uses: mikepenz/action-junit-report@v3
+          if: success() || failure() # always run even if the previous step fails
+          with:
+            report_paths: '**/junit.xml'
+            detailed_summary: true
+            include_passed: true
+ 
